### ISSUE TITLE
Current environment.yml should not be solvable?

### ISSUE THREAD

**Issue by davidbrochart** [xtensor-stack/xtensor-io#125]
In [environment.yml](https://github.com/xtensor-stack/xtensor-io/blob/master/environment.yml) we have:
- `xtensor-io=0.10.3`, which requires `openimageio >=2.1,<2.2` (see https://github.com/conda-forge/xtensor-io-feedstock/blob/master/recipe/meta.yaml)
- `ffmpeg=3.4.2`

But `mamba create -n xtensor-io ffmpeg=3.4.2 openimageio=2.1` results in:
```
Problem: package openimageio-2.1.10-h81b2a71_1 requires ffmpeg >=4.1.3,<4.2.0a0, but none of the providers can be installed
```
So I don't understand how [the binder](https://mybinder.org/v2/gh/xtensor-stack/xtensor-io/stable?filepath=notebooks%2Fdemo.ipynb) can build.

**Comment by JohanMabille** [comment]
The binder uses the stbale branch, which points to 0.8.0 version. This should be fixed and the stable branch should be updated
