### ISSUE TITLE
Add xexpression interface to HDF5 

### ISSUE THREAD

**Issue by wolfv** [xtensor-stack/xtensor-io#47]
Currently the HDF5 functions can create a HDF5 data structure from xarray or xtensor. xtensor_fixed is not yet supported.

If we'd take an xexpression, we could create an HDF5 object seamlessly from: pyarray / rarray / views / xtensor_fixed ...

**Comment by wolfv** [comment]
we'd need to change the function signature to read something like:

```
template <class E>
auto func(const xexpression<E>& expr)
{
     auto& d = expr.derived_cast(); // the real, underlying expression
     d.begin() / d.end() ... all work here!
}
```

Where the "real" expression type is in the `E` template variable. Calling derived_cast() get's a reference to the underlying expression. So the expression type for xarray would be `xexpression<xarray<double>>`.
The good thing about the xexpression argument is that it will only accept arguments whose classes are derived from xexpression, which is only true for "our" classes (and not std::vector etc).

Does that make sense?

**Comment by tdegeus** [comment]
I was starting to think about this again. Since HighFive now supports all types with `H5Easy::dump(...)` and `H5Easy::load(...)`, the xtensor-io functions could simply support xtensor only, but with a much wider scope.
