### ISSUE TITLE
Adding an interface for GDAL

### ISSUE THREAD

**Issue by andrew-hardin** [xtensor-stack/xtensor-io#73]
GDAL is a translator library for geospatial raster data (e.g. satellite imagery). Would this project be receptive to a PR that enables reading/writing raster files using GDAL? The implementation would look very similar to the existing interface into `OpenImageIO`.

**Comment by wolfv** [comment]
definitely! PR's very welcome :)

**Comment by wolfv** [comment]
thanks @andrew-hardin
